// src/types/review.ts
import { Timestamp } from "firebase/firestore";

export interface Review {
  id: string;
  bookId: string;
  userId: string;
  userName: string; // Cached display name
  rating: number; // 1 to 5
  comment: string;
  createdAt: Timestamp | Date;
}

// We use this type when creating a review (ID and Date are generated by DB)
export type NewReviewData = Omit<Review, "id" | "createdAt">;
